
cc_test(
    name = "test_parseseperatevalues",
    srcs = ["test_parseseperatevalues.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib/parseseperatevalues:parseseperatevalues"
        ],
    visibility = ["//visibility:public"],
)

