
cc_test(
    name = "test_fileinput",
    srcs = ["test_fileinput.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib/fileinput:fileinput"
        ],
    visibility = ["//visibility:public"],
)

